version: '2'
services:
  pytorch:
    build: .
    volumes:
      - .:/app
      - /data:/data:ro
      - /fastdata:/fastdata:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/hostname:/etc/hostname:ro
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - DISPLAY
      - PYTHONIOENCODING=utf_8
    ipc: host
  showoff:
    image: anibali/showoff:pytorch-dsnt
    ports:
      - "16676:3000"
    env_file:
      - ./env/postgres.env
    links:
      - db
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=showoff_db
    env_file:
      - ./env/postgres.env
    volumes:
      - showoff_data:/var/lib/postgresql/data

volumes:
  showoff_data:
    external: false
