services:
  db:
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    env_file:
    - ./env/postgres.env
    environment:
    - POSTGRES_DB=showoff_db
    image: postgres:9.5
    volumes:
    - showoff_data:/var/lib/postgresql/data
    - nvidia_driver_375.51:/usr/local/nvidia:ro
  pytorch:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - DISPLAY
    - PYTHONIOENCODING=utf_8
    ipc: host
    volumes:
    - .:/app
    - /data:/data:ro
    - /etc/localtime:/etc/localtime:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /etc/hostname:/etc/hostname:ro
    - nvidia_driver_375.51:/usr/local/nvidia:ro
  showoff:
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    env_file:
    - ./env/postgres.env
    image: showoff
    links:
    - db
    ports:
    - 16676:3000
    volumes:
    - nvidia_driver_375.51:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_375.51:
    external: true
  showoff_data:
    external: false
