apiVersion: v1
kind: Pod
metadata:
  name: train-resnet50-reg
spec:
  restartPolicy: Never
  hostIPC: true
  containers:
  - name: train-resnet50-reg
    image: registry.dl.cs.latrobe.edu.au/aiden/dsnt
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
    args: ["src/dsnt/bin/train.py", "--base-model=resnet50",  "--dilate=2", "--output-strat=dsnt",
           "--reg=js", "--showoff="]
    env:
    - name: PYTHONIOENCODING
      value: utf_8
    volumeMounts:
    - mountPath: /datasets/mpii
      name: mpii
      readOnly: true
    - mountPath: /app/out
      name: output
    - mountPath: /home/user/.torch/models
      name: pretrained-models
  volumes:
  - name: mpii
    hostPath:
      path: /nfs/datasets/public/MPII_Human_Pose
      type: Directory
  - name: output
    hostPath:
      path: /nfs/users/aiden/dsnt-out
      type: DirectoryOrCreate
  - name: pretrained-models
    hostPath:
      path: /nfs/models/pytorch
      type: DirectoryOrCreate
